# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ractions.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x05Tuple\x12&\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x16.google.protobuf.Value\"5\n\rOptionalTuple\x12\x1a\n\x05tuple\x18\x01 \x01(\x0b\x32\x06.TupleH\x00\x88\x01\x01\x42\x08\n\x06_tuple\"1\n\x07Pattern\x12&\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x16.google.protobuf.Value2\xa2\x01\n\x07\x41\x63tions\x12%\n\x03Out\x12\x06.Tuple\x1a\x16.google.protobuf.Empty\x12\x16\n\x02In\x12\x08.Pattern\x1a\x06.Tuple\x12\x16\n\x02Rd\x12\x08.Pattern\x1a\x06.Tuple\x12\x1f\n\x03Inp\x12\x08.Pattern\x1a\x0e.OptionalTuple\x12\x1f\n\x03Rdp\x12\x08.Pattern\x1a\x0e.OptionalTupleB@\n(com.djordjemilanovic.lindasharp.services\xaa\x02\x13LindaSharp.Servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.djordjemilanovic.lindasharp.services\252\002\023LindaSharp.Services'
  _globals['_TUPLE']._serialized_start=76
  _globals['_TUPLE']._serialized_end=123
  _globals['_OPTIONALTUPLE']._serialized_start=125
  _globals['_OPTIONALTUPLE']._serialized_end=178
  _globals['_PATTERN']._serialized_start=180
  _globals['_PATTERN']._serialized_end=229
  _globals['_ACTIONS']._serialized_start=232
  _globals['_ACTIONS']._serialized_end=394
# @@protoc_insertion_point(module_scope)
