# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfc\x01\n\x15ScriptExecutionStatus\x12+\n\tnot_found\x18\x01 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12$\n\x02ok\x18\x02 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12\x35\n\texception\x18\x03 \x01(\x0b\x32 .ScriptExecutionStatus.ExceptionH\x00\x1aO\n\tException\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x13\n\x0bstack_trace\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\tB\x08\n\x06status2\x97\x01\n\x06Health\x12<\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\x12O\n\x18GetScriptExecutionStatus\x12\x1b.google.protobuf.Int32Value\x1a\x16.ScriptExecutionStatusB@\n(com.djordjemilanovic.lindasharp.services\xaa\x02\x13LindaSharp.Servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.djordjemilanovic.lindasharp.services\252\002\023LindaSharp.Services'
  _globals['_SCRIPTEXECUTIONSTATUS']._serialized_start=78
  _globals['_SCRIPTEXECUTIONSTATUS']._serialized_end=330
  _globals['_SCRIPTEXECUTIONSTATUS_EXCEPTION']._serialized_start=241
  _globals['_SCRIPTEXECUTIONSTATUS_EXCEPTION']._serialized_end=320
  _globals['_HEALTH']._serialized_start=333
  _globals['_HEALTH']._serialized_end=484
# @@protoc_insertion_point(module_scope)
