# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scripts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscripts.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"W\n\x06Script\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.Script.Type\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"#\n\x04Type\x12\x0e\n\nIRONPYTHON\x10\x00\x12\x0b\n\x07\x43_SHARP\x10\x01\"=\n\x15RegisterScriptRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x06script\x18\x02 \x01(\x0b\x32\x07.Script\"`\n\x13InvokeScriptRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\tparameter\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueH\x00\x88\x01\x01\x42\x0c\n\n_parameter\",\n\x11\x45valScriptRequest\x12\x17\n\x06script\x18\x01 \x01(\x0b\x32\x07.Script\"%\n\x12\x45valScriptResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x32\xab\x01\n\x07Scripts\x12:\n\x08Register\x12\x16.RegisterScriptRequest\x1a\x16.google.protobuf.Empty\x12\x33\n\x06Invoke\x12\x14.InvokeScriptRequest\x1a\x13.EvalScriptResponse\x12/\n\x04\x45val\x12\x12.EvalScriptRequest\x1a\x13.EvalScriptResponseB@\n(com.djordjemilanovic.lindasharp.services\xaa\x02\x13LindaSharp.Servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scripts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.djordjemilanovic.lindasharp.services\252\002\023LindaSharp.Services'
  _globals['_SCRIPT']._serialized_start=76
  _globals['_SCRIPT']._serialized_end=163
  _globals['_SCRIPT_TYPE']._serialized_start=128
  _globals['_SCRIPT_TYPE']._serialized_end=163
  _globals['_REGISTERSCRIPTREQUEST']._serialized_start=165
  _globals['_REGISTERSCRIPTREQUEST']._serialized_end=226
  _globals['_INVOKESCRIPTREQUEST']._serialized_start=228
  _globals['_INVOKESCRIPTREQUEST']._serialized_end=324
  _globals['_EVALSCRIPTREQUEST']._serialized_start=326
  _globals['_EVALSCRIPTREQUEST']._serialized_end=370
  _globals['_EVALSCRIPTRESPONSE']._serialized_start=372
  _globals['_EVALSCRIPTRESPONSE']._serialized_end=409
  _globals['_SCRIPTS']._serialized_start=412
  _globals['_SCRIPTS']._serialized_end=583
# @@protoc_insertion_point(module_scope)
